"""Markdown output generation for transcript analysis."""

from datetime import datetime
from pathlib import Path

from meetingmind.models import TranscriptAnalysis


def generate_markdown(analysis: TranscriptAnalysis) -> str:
    """Generate a formatted markdown document from transcript analysis."""
    title = (analysis.metadata.title if analysis.metadata else None) or Path(
        analysis.source_file
    ).stem
    lines = [
        f"# {title}",
        "",
        f"**Source:** `{analysis.source_file}`",
        f"**Processed:** {analysis.processed_at.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "---",
        "",
    ]

    # Summary section
    lines.extend(
        [
            "## 📋 Summary",
            "",
            analysis.summary.content,
            "",
        ]
    )

    if analysis.summary.key_topics:
        lines.extend(
            [
                "**Key Topics:**",
                "",
            ]
        )
        for topic in analysis.summary.key_topics:
            lines.append(f"- {topic}")
        lines.append("")

    # Action Points section
    lines.extend(
        [
            "## ✅ Action Points",
            "",
        ]
    )

    if analysis.action_points.items:
        for i, action in enumerate(analysis.action_points.items, 1):
            priority_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}
            emoji = priority_emoji.get(action.priority, "⚪")

            lines.append(f"### {i}. {emoji} {action.description}")
            if action.owner:
                lines.append(f"- **Owner:** {action.owner}")
            if action.deadline:
                lines.append(f"- **Deadline:** {action.deadline}")
            lines.append(f"- **Priority:** {action.priority.capitalize()}")
            lines.append("")
    else:
        lines.extend(["*No action points identified.*", ""])

    # Todo List section
    lines.extend(
        [
            "## 📝 Todo List",
            "",
        ]
    )

    if analysis.todo_list.items:
        for item in analysis.todo_list.items:
            lines.append(f"- [ ] {item.task}")
            if item.context:
                lines.append(f"  - *Context: {item.context}*")
        lines.append("")
    else:
        lines.extend(["*No todo items identified.*", ""])

    # Important Mentions section
    lines.extend(
        [
            "## 👥 Important Mentions",
            "",
        ]
    )

    if analysis.important_mentions.items:
        for mention in analysis.important_mentions.items:
            lines.append(f"### {mention.person}")
            lines.append(f"- **Context:** {mention.context}")
            lines.append(f"- **Significance:** {mention.significance}")
            lines.append("")
    else:
        lines.extend(["*No important mentions identified.*", ""])

    # Recap section
    lines.extend(
        [
            "## 🔄 Recap",
            "",
        ]
    )

    if analysis.recap.highlights:
        lines.extend(["**Highlights:**", ""])
        for highlight in analysis.recap.highlights:
            lines.append(f"- {highlight}")
        lines.append("")

    if analysis.recap.decisions_made:
        lines.extend(["**Decisions Made:**", ""])
        for decision in analysis.recap.decisions_made:
            lines.append(f"- {decision}")
        lines.append("")

    if analysis.recap.next_steps:
        lines.extend(["**Next Steps:**", ""])
        for step in analysis.recap.next_steps:
            lines.append(f"- {step}")
        lines.append("")

    # Meeting Tone section
    lines.extend(
        [
            "## 🎭 Meeting Tone",
            "",
            f"- **Overall Sentiment:** {analysis.meeting_tone.overall_sentiment.capitalize()}",
            f"- **Energy Level:** {analysis.meeting_tone.energy_level.capitalize()}",
            f"- **Collaboration Quality:** {analysis.meeting_tone.collaboration_quality.capitalize()}",
        ]
    )

    if analysis.meeting_tone.notes:
        lines.extend(
            [
                "",
                f"**Notes:** {analysis.meeting_tone.notes}",
            ]
        )

    lines.append("")

    # Key Insights section
    lines.extend(
        [
            "## 💡 Key Insights",
            "",
        ]
    )

    if analysis.key_insights.insights:
        lines.extend(["**Insights:**", ""])
        for insight in analysis.key_insights.insights:
            lines.append(f"- {insight}")
        lines.append("")

    if analysis.key_insights.patterns:
        lines.extend(["**Patterns:**", ""])
        for pattern in analysis.key_insights.patterns:
            lines.append(f"- {pattern}")
        lines.append("")

    if analysis.key_insights.recommendations:
        lines.extend(["**Recommendations:**", ""])
        for rec in analysis.key_insights.recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    # Footer
    lines.extend(
        [
            "---",
            "",
            "*Generated by MeetingMind*",
        ]
    )

    return "\n".join(lines)


def generate_output_filename(
    template: str,
    source_file: Path,
    processed_at: datetime,
    meeting_datetime: datetime | None = None,
) -> str:
    """Generate output filename from template with placeholders.

    Supported placeholders:
    - {source_stem}: Original filename without extension
    - {timestamp}: Processing timestamp in YYYYMMDD_HHMMSS format (kept for compatibility)
    - {meeting_timestamp}: Meeting datetime in YYYYMMDD_HHMMSS format; falls back to processed_at
    """
    meeting_ts = (meeting_datetime or processed_at).strftime("%Y%m%d_%H%M%S")
    replacements = {
        "source_stem": source_file.stem,
        "timestamp": processed_at.strftime("%Y%m%d_%H%M%S"),
        "meeting_timestamp": meeting_ts,
    }

    result = template
    for key, value in replacements.items():
        result = result.replace(f"{{{key}}}", value)

    return result
